bioloidgp_social_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_6
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_7
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint8_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_8
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint9_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_9
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint10_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_10
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint11_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_11
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint12_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_12
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint13_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_13
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint14_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_14
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint15_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_15
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint16_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_16
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint17_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_17
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint18_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_18
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint19_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_19
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint20_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_20
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint21_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_21
    pid: {p: 100.0, i: 0.01, d: 10.0}
    