joint:
  names: [right_leg_1, right_leg_2]
motion:
  names: [right, zero, left]
  right:
    step: [-1, -1]  # radian
    time_from_start: 2.0  # sec
  zero:
    step: [0.0, 0.0]
    time_from_start: 3.0
  left:
    step: [1, 1]
    time_from_start: 6.0

