# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0

camera_vertical:
  ID: 21
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

camera_horizontal:
  ID: 20
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

torso:
  ID: 19
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_arm_1:
  ID: 1
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_arm_2:
  ID: 3
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_arm_3:
  ID: 5
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_gripper:
  ID: 7
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_arm_1:
  ID: 2
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_arm_2:
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_arm_3:
  ID: 6
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_gripper:
  ID: 8
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_leg_1:
  ID: 9
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_leg_2:
  ID: 11
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_leg_3:
  ID: 13
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_leg_4:
  ID: 15
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

right_leg_5:
  ID: 17
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_leg_1:
  ID: 10
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_leg_2:
  ID: 12
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_leg_3:
  ID: 14
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_leg_4:
  ID: 16
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

left_leg_5:
  ID: 18
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983