# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_3
    - joint_5
    - joint_10
    - joint_12
    - joint_14
    - joint_16
    - joint_18
    - joint_9
    - joint_11
    - joint_13
    - joint_15
    - joint_17
    - joint_2
    - joint_4
    - joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: rigth_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_3
      - joint_5
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_4
      - joint_6
  - name: right_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_9
      - joint_11
      - joint_13
      - joint_15
      - joint_17
  - name: left_leg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_10
      - joint_12
      - joint_14
      - joint_16
      - joint_18
  - name: body_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_3
      - joint_5
      - joint_10
      - joint_12
      - joint_14
      - joint_16
      - joint_18
      - joint_9
      - joint_11
      - joint_13
      - joint_15
      - joint_17
      - joint_4
      - joint_6