right_leg_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: waist_joint
    joint_speed: 0.17
    motor:
        id: 9
        init: 512
        min: 0
        max: 1023
        
right_leg_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: femur_joint
    joint_speed: 0.17
    motor:
        id: 11
        init: 512
        min: 0
        max: 1023

right_leg_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: knee_joint
    joint_speed: 0.17
    motor:
        id: 13
        init: 512
        min: 0
        max: 1023

right_leg_4:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: foot_joint
    joint_speed: 0.17
    motor:
        id: 15
        init: 512
        min: 0
        max: 1023

right_leg_5:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: foot_instep_joint
    joint_speed: 0.17
    motor:
        id: 17
        init: 512
        min: 300
        max: 600