right_arm_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_shoulder_joint
    joint_speed: 0.17
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023
        
right_arm_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_arm_joint
    joint_speed: 0.17
    motor:
        id: 3
        init: 512
        min: 0
        max: 1023

right_arm_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_forearm_joint
    joint_speed: 0.17
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023

right_gripper:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_gripper_joint
    joint_speed: 0.17
    motor:
        id: 7
        init: 512
        min: 0
        max: 1023

left_arm_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_shoulder_joint
    joint_speed: 0.17
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023
        
left_arm_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_arm_joint
    joint_speed: 0.17
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023

left_arm_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_forearm_joint
    joint_speed: 0.17
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023

left_gripper:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_gripper_joint
    joint_speed: 0.17
    motor:
        id: 8
        init: 512
        min: 0
        max: 1023

torso:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: torso_joint
    joint_speed: 0.17
    motor:
        id: 19
        init: 512
        min: 0
        max: 1023

right_leg_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_waist_joint
    joint_speed: 0.17
    motor:
        id: 9
        init: 512
        min: 0
        max: 1023
        
right_leg_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_femur_joint
    joint_speed: 0.17
    motor:
        id: 11
        init: 512
        min: 0
        max: 1023

right_leg_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_knee_joint
    joint_speed: 0.17
    motor:
        id: 13
        init: 512
        min: 0
        max: 1023

right_leg_4:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_foot_joint
    joint_speed: 0.17
    motor:
        id: 15
        init: 512
        min: 0
        max: 1023

right_leg_5:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: right_foot_instep_joint
    joint_speed: 0.17
    motor:
        id: 17
        init: 512
        min: 300
        max: 600

left_leg_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_waist_joint
    joint_speed: 0.17
    motor:
        id: 10
        init: 512
        min: 0
        max: 1023
        
left_leg_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_femur_joint
    joint_speed: 0.17
    motor:
        id: 12
        init: 512
        min: 0
        max: 1023

left_leg_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_knee_joint
    joint_speed: 0.17
    motor:
        id: 14
        init: 512
        min: 0
        max: 1023

left_leg_4:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_foot_joint
    joint_speed: 0.17
    motor:
        id: 16
        init: 512
        min: 0
        max: 1023

left_leg_5:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: left_foot_instep_joint
    joint_speed: 0.17
    motor:
        id: 18
        init: 512
        min: 300
        max: 600