# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0

joint_1:
  ID: 1
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_2:
  ID: 2
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_3:
  ID: 3
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_4:
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_5:
  ID: 5
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_6:
  ID: 6
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_7:
  ID: 7
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_8:
  ID: 8
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_9:
  ID: 9
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_10:
  ID: 10
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_11:
  ID: 11
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_12:
  ID: 12
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_13:
  ID: 13
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_14:
  ID: 14
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_15:
  ID: 15
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_16:
  ID: 16
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_17:
  ID: 17
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_18:
  ID: 18
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 75
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_19:
  ID: 19
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_20:
  ID: 20
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983

joint_21:
  ID: 21
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Temperature_Limit: 70
  Min_Voltage_Limit: 60
  Max_Voltage_Limit: 140
  Max_Torque: 983